/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'morteza' at '12/13/16 6:04 AM' with Gradle 3.2.1
 *
 * @author morteza, @date 12/13/16 6:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
